### ISSUE TITLE
When Item broken it removes all items of that type

### ISSUE THREAD

**Issue by smartaleq** [smartaleq/DwarfCraft_orig#12]
I had an unused diamond pickaxe and one that was just about to break in my inventory. I used the near-broken one until it did break. When it broke, both of the diamond pickaxes in my inventory perished. So, so sad. :(

**Comment by smartaleq** [comment]
Resolved, new toolchecker removes only one item slot at a time now.

error was caused due to using .remove(itemstack) which removes all matching itemstacks for QTY and MATERIAL but ignoring damage/data

**Comment by RCarretta** [comment]
I assume you just changed inv.remove() to inv.removeItem()?

**Comment by smartaleq** [comment]
no, that doesn't actually work. I had to get the contents and set qty to 0 for that stack then setContents. RemoveItem also doesn't see durability

**Comment by RCarretta** [comment]
it seems to work when i do it. on my branch (code running on server atm) that's the only change I made and it isn't having issues.
