### ISSUE TITLE
Implement variable dig speed

### ISSUE THREAD

**Issue by smartaleq** [smartaleq/DwarfCraft_orig#19]
on hold until bukkit implements a way to do this or creative workaround devised

**Comment by RCarretta** [comment]
I think this skill should be removed from DwarfCraft. With the reduction in training costs I don't see a need to be able to mine 'faster', as this acts as a multiplier on resource gathering on top of getting more material.

Additionally, I think the animations for block destruction are handled clientside, which, if true, would make implementation of this not possible. Consider that if two people mine the same block at the same time it doesn't get destroyed twice as fast.

**Comment by smartaleq** [comment]
mining faster has a key benefit besides more material gained: faster area clearing. even if there is a cap on dig speed, it would be a worthwhile skill to have stone picks mine as fast as iron, or iron as fast as diamond

coding challenges are severe, and recognized, keeping this on hold until bukkit provides affordances or we decide to nix this entirely

**Comment by smartaleq** [comment]
reimplementing as % chance to insta-mine a block, affecting only primary blocks (dirt, sand, gravel, log, cbble, stone)

**Comment by smartaleq** [comment]
working
