### ISSUE TITLE
Implement boat move effects

### ISSUE THREAD

**Issue by smartaleq** [smartaleq/DwarfCraft_orig#20]
VEHICLEMOVE on movement

**Comment by RCarretta** [comment]
Could you separate these out? I have an idea for the movement.

**Comment by smartaleq** [comment]
Keep this issue for vehicleMove, vehicle drop is closed.

**Comment by RCarretta** [comment]
I can clearly make boats move faster using teleportTo, and keeping tracking information local to DC. Issues right now are that the player precedes the boat ~3 blocks (maybe I can teleport the player as well...?), causing the player to get stuck in land whenever the boat approaches land. Also the direction of the boat doesn't change. This should be easy to rectify.

**Comment by smartaleq** [comment]
resolved implementation and made specific to boats
