### ISSUE TITLE
Implement backwards database compatibility for release agility

### ISSUE THREAD

**Issue by RCarretta** [smartaleq/DwarfCraft_orig#26]
New releases should be able to implement new skills without requiring deletion of all players, etc.

**Comment by smartaleq** [comment]
making major strides here, completely refactored large parts of datamanager and configmanager

**Comment by smartaleq** [comment]
also added file versioning

**Comment by smartaleq** [comment]
this is done, needs to be tested/vetted

**Comment by RCarretta** [comment]
Does it both gracefully handle addition/removal of any skill/effect/school/school format?

**Comment by smartaleq** [comment]
believe this is working
