### ISSUE TITLE
Refactor offline dwarf skilldata into Datamanager

### ISSUE THREAD

**Issue by smartaleq** [smartaleq/DwarfCraft_orig#27]
moving dwarf.find(name) to call a datamanager function

**Comment by smartaleq** [comment]
this is done, needs to be tested/vetted, please

**Comment by RCarretta** [comment]
Is this officially complete? I'd like to review the code, but don't want to do so until you're happy with it. I know there were some issues tonight, not sure if it was this area.

**Comment by smartaleq** [comment]
yes, this is complete

**Comment by smartaleq** [comment]
it works, closing
