### ISSUE TITLE
Make schools NPC-able

### ISSUE THREAD

**Issue by smartaleq** [smartaleq/DwarfCraft_orig#35]
accidently closed this one, oops

ok, consider this....

school "zones" continue to exist, they are placed by anyone with permissions. (eventually town mayors)

npcs are either of the "greeter" or "trainer" type, with associated left-click and right-click actions. are placed by anyone with permissions (eventually town mayors). trainers have a skill# specified when placed, greeters have nothing specified (or skill#0 means greeter)

interacting with a greeter results in a check for the zone the greeter is in, driving the messages displayed. leftclick= welcome to the School school, here you can train x y and z skills, which help you do a b and c types of things.
rightclick = "to find out about a skill and what it does for you, left click a skill trainer, to ask a trainer to instruct you, right click him"

interacting with a trainer checks the trainer's skill and leftclick = skillinfo/traininfo/effects
right click = /dc train skillid

**Comment by RCarretta** [comment]
You can reopen things you've closed in the same way you add tags.

Based on what you've said, what value-add do the school zones present? Isn't this something that could be handled on the greeters directly rather than jumping through hoops to see if they are in a zone?

**Comment by smartaleq** [comment]
i'm not sure they add any. they are in and working, but may be a solution looking for a problem.at the very least, they bridge us to 1.0 if NPCs aren't ready.

on reason i like the zones system is that by using area-exclusive zones (non-overlapping) you force trainers to be more separate, instead of a town mayor just making a big ugly room with 50 npcs in it

**Comment by RCarretta** [comment]
I think if the mayor wants to have an ugly town that's their prerogative on their server, yes? There isn't going to be a great deal you can do to influence uglyness. :-P Even with non-overlapping zones certainly you could work around it if your goal was merely to get the schools down.

I have a good bit of this written, though there is a lot more to do yet.

**Comment by RCarretta** [comment]
schools fully in and working now. just need more testing and better interface for commands/etc.

**Comment by smartaleq** [comment]
this is working. closing this ticket, reopen new tickets with specific bugs
