### ISSUE TITLE
Tutorial and help are outdated

### ISSUE THREAD

**Issue by dancaselden** [smartaleq/DwarfCraft_orig#41]
Told to use /dc skillsheet, where the current syntax is /dc skillsheet <playername>

Told to use /dc schoolinfo, where the current syntax is /dc schoolinfo <school number>

**Comment by smartaleq** [comment]
for whoever wants the task: rewrite tutorial entirely.... dan?

**Comment by dancaselden** [comment]
I would write into the tutorial that it is outdated, and revisit just before release (once command syntax is finalized)

**Comment by smartaleq** [comment]
updated
