### ISSUE TITLE
Tutorial command syntax change request

### ISSUE THREAD

**Issue by dancaselden** [smartaleq/DwarfCraft_orig#43]
Feature request to change /dc tutorial, /dc tutorial2, etc... to behave as follows:

/dc tutorial
/dc tutorial1
/dc tutorial 1
return the first tutorial page

/dc tutorial2
/dc tutorial 2
return the second page

and so on. Or, stick strictly with the /dc <command> <argument> syntax.

**Comment by smartaleq** [comment]
request accepted, will do

**Comment by RCarretta** [comment]
your ship will now be towed into the docking bay

**Comment by dancaselden** [comment]
dockin--dock--dock--dock--docking request ac-cep-ted

**Comment by smartaleq** [comment]
CTD

**Comment by smartaleq** [comment]
imple-impl-imp-implemented

**Comment by dancaselden** [comment]
Please add /dc tutorial with no argument as an alias for /dc tutorial 1
