### ISSUE TITLE
Falling damage modifier on the climbing skills

### ISSUE THREAD

**Issue by dancaselden** [smartaleq/DwarfCraft_orig#45]
Dan thinks it's too annoying. He felt that falling too short a distance resulted in damage in the original Minecraft, but that since the damage was small and frequent, that it added value for food. He feels that the short falling distance with increased damage modifier becomes so annoying that the added value to food is not worth it.

And screw your pumpkins.

**Comment by smartaleq** [comment]
go jump off a 15 foot ledge and tell me you're ok... yeah, thats right I'm using real-world numbers to make a specious argument about an ingame balance choice i made because i hate dan specifically.

FACE

**Comment by dancaselden** [comment]
One minecraft man is barely shorter than two blocks. Taking the approximate average height of a U.S. human male (5'10"), rounded up to 6" to accomodate for the difference between the minecraft man and the two block height, we get 3" (6"/2blocks) per block.

It follows that 3.000000000000001 blocks (the minimum falling distance required to take damage) would total approximately 9". Required for v1.0, further statistical analysis on human injuries due to falling in excess of 9". Until such analyses are completed, it is recommended that falling damage be omitted from the DwarfCraft plugin.
