### ISSUE TITLE
general command consistency

### ISSUE THREAD

**Issue by dancaselden** [smartaleq/DwarfCraft_orig#50]
I'd advise adhering to a common syntax and behavior for command-line arguments.

For example, /dc help, if to be similar to bash, should return the command list. This would displace the welcome and about text currently displayed in /dc help, so perhaps move that to /dc about.

Commands should not be numbered (tutorial 2, tutorial 3, instead of tutorial2, tutorial3).

Each command should have its own help display (such as /dc train -h, /dc train --help, /dc train /? or /dc help train)

Commands that take arguments, when called with improper arguments, should always reply with an error, and perhaps suggest the command to obtain more help (like /dc train BALLSACKS: (Input Error) Skill "BALLSACKS" not found.\nType /dc help train for assistance)

Any error upon a user typing a command should return something to the user, even if it is "[DC] Internal error."

**Comment by smartaleq** [comment]
fixt throughout, and fuck you, friend

**Comment by dancaselden** [comment]
;)
