### ISSUE TITLE
Trainers ignore maxSkill.

### ISSUE THREAD

**Issue by Medalink** [smartaleq/DwarfCraft_orig#63]
Command Used:

/createtrainer Nordan Nordan 1 10

Expected:

NPC Trainer that teaches pickaxe skill up to 10.

Got:

NPC Trainer that teaches pickaxe beyond level 10.

SQL Used:

INSERT INTO trainers VALUES('Nova','Nordan','Nordan (Pickaxe Trainer)',1,10,257,0,NULL,-732.529833179526,73.0,551.050960672585,-180.900680541992,17.2499866485596);

**Comment by Medalink** [comment]
I went back to this same trainer and he now says I can't train from him... not sure what caused that but he is working now with no changes.

What has changed since then?

Updated Bukkit to the latest (was 531 now 555).

**Comment by tcamara7** [comment]
I believe that the skill you set adds 1, for instance, I set my trainers to 19 and they'll train to 20 but no more

**Comment by smartaleq** [comment]
resolved, thanks for the report information
