### ISSUE TITLE
Trainers causing fake dupe items

### ISSUE THREAD

**Issue by Medalink** [smartaleq/DwarfCraft_orig#71]
I spawned a pickaxe trainer and gather the cobblestone required to level (in my inventory). I right clicked and got the training (went from 0 to 1). However in my inventory I still show I have the same amount of cobblestone as I did pre-levelup. Upon further review (such as picking up the "ghost" stack it disappears.

So trainers are taking the items but the client (or something) is not quite registering this.

This happens with other trainers as well.

**Comment by smartaleq** [comment]
fixed
