### ISSUE TITLE
Using a sheep returns 36 wool....

### ISSUE THREAD

**Issue by Medalink** [smartaleq/DwarfCraft_orig#72]
So I got animal hunter to level 7 and I clicked a sheep to receive 36 wool. I did it again on another sheep and same thing. This happens over and over, this can't be right?

2011-03-14 16:40:36 [INFO] DC6: PVE Medalink attacked CraftSheep for 0.85 of 5 doing 5 dmg of 5hp effect called:871

effects.config:

871,0.75,0.05,0,0,100,FALSE,FALSE,0,0,0,5,PVEDAMAGE,0,0,FALSE,268,272,267,283,276

Is this an invalid config set or some problem with the code?

**Comment by smartaleq** [comment]
probably an invalid config setup somewhere. 36 is the itemcode for wool, so it sounds like its dropping 36 of 36. I'll take a look.

**Comment by smartaleq** [comment]
did you modify your effects.config? the relevant line isn't the PVEDAMAGE one but the MOBDROP #812

**Comment by Medalink** [comment]
Since it was calling the 871 that's what I posted. I am using the default config.

812:
812,1.25,0.2,0,0,6,FALSE,FALSE,0,0,0,5,MOBDROP,0,35,TRUE,268,272,267,283,276

**Comment by smartaleq** [comment]
could not reproduce

**Comment by Medalink** [comment]
I have not been able to reproduce it either. It happened the one time (well for a bit until I restarted) and not since.

**Comment by smartaleq** [comment]
closing, thanks
