### ISSUE TITLE
Minecart top speed is too high

### ISSUE THREAD

**Issue by snidelycapon** [smartaleq/DwarfCraft_orig#79]
Something in the plugin is messing around with the speed of minecarts, causing them to move many times faster than they should. Using DwarfCraft with Minecart Mania results in the cart derailing at the first corner and embedding the player into the wall, suffocating them.

Is there a connection between boat speed and Minecart speed? Particularly the "max speed" value, which I think is what's causing the problems - MM works assuming the vanilla hard-cap is on minecart speed (8m/s if I recall,) but if you've removed/raised that cap in order to accommodate the Sailor skill, the booster chains in my stations would very quickly blast it up far past normal into ludicrous speeds - if I wasn't getting suffocated almost instantly I'd expect everything to go plaid.

**Comment by smartaleq** [comment]
Dwarfcraft vehicle code is not checking for vehicle type before modifying speed. Ryan, this is up to you.

**Comment by smartaleq** [comment]
with help from rcarretta, this is resolved.

**Comment by snidelycapon** [comment]
You guys rule. Thanks for all the hard work!
